language: php

env:
  global:
    - WP_VERSION=master
    - WP_VERSION=4.6
    - SVN_REPO: https://plugins.svn.wordpress.org/stormpath/
    - secure: "jxrEjvllmL7fmfVX7GxwHmbShBVJ+/s6pjzZdwmnVzIOMg6XGP1+6xmCJ23VDlJh7lA+FSqfw2dYHletBicwjYCPDzvZyrIhO6Qr7p00RiyUS+8JuYiJBTU2SWMW3Fq4CyCBS7sJF1xCCpZ/gu0PsZqjA+M6+s8Gu9/4NaOF1mXh664CzPFMAlXrcKh59IO2ML0Op+4c8pzWUw0B6INQ4/wsUTCYSenGSaur7USEJQKVELmHnyQ7HMhvrbf7+AiRVtgK+0BVLKdLhoNmO+bdTbCHz7wtHhmCLcjyztXaVJ9mWvinc8IUcWTsvaqxbldvQh2gCy5SHwPyVp5gPScC/u7OqXYadjqdK1CfZ9H8Q5PGxmQbZmzSsKPbhoR1CCzM2YY12WxYCKgg6htK2dLtgyKKA/pfN6Bvn1YMnOUdCvIkE2SF11oofhH6KYz7jNwMAxaatwhcsxeEYeQ0Fbt6RI+sriFAeReD5pcu3USVxbsn3B8GN/kk101bilcOdQQO2IIndDhNgfoagKQThhgkhHXuPTDo/p9ZrEWxF2UJt8RF9LLWMQxqtVpAYLRuaLLFYjvwfwdHKpSvmx97NZf6tbb6pFJkfGLDeb1wZJwwZS92S9K21JJLLiyOoZ2A+Um9W3cHHvemXHOxjTPNYff5j8AkrmBmTVNBNZTZazMpmuM="

matrix:
  include:
    - php: 7.0
      env: WP_VERSION=latest WP_MULTISITE=0 WP_PULUGIN_DEPLOY=1

before_script:
  - composer install --prefer-source
  - mkdir -p build/logs

script:
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

cache:
  directories:
    - vendor/

after_success:
  - bash deploy.sh